### ISSUE TITLE
Fefosheep keeps repeatedly looping the download

### ISSUE THREAD

**Issue by astronautlevel2** [kekmaster97/fefosheep#1]
Help I try to install FEFOSHEEP to get FRII GAM but it keeps looping the download

:thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking:

**Comment by Sixardyh** [comment]
This is fucking piracy you autistic fuck

**Comment by astronautlevel2** [comment]
You were warned on Nintendo Homebrew. The given reason is: r1

**Comment by ghost** [comment]
Hyaxo appealed his warn for astro being nazi mod!!!!!!!!!

**Comment by GriffinG1** [comment]
.warn @astronautlevel2  Nazi Mod

**Comment by deathgripsfanwiki** [comment]
Who do you think you are, you lazy dev

**Comment by T3CHNOLOG1C** [comment]
.sr retards are arguing again (xd reviving ded issue)
